### ISSUE TITLE
Pyhdb.connect fails because of Unknown Option Type

### ISSUE THREAD

**Issue by jayanthjaiswal** [SAP/PyHDB#6] opened 2015-02-20 13:34 UTC
Hi all,

It threw the following error while connecting:

Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/__init__.py", line 10, in connect
    connection.connect()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/client.py", line 126, in connect
    ConnectOptions(DEFAULT_CONNECTION_OPTIONS)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/protocol/base.py", line 87, in send
    return self.connection._send_message(self.pack())
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/client.py", line 96, in _send_message
    return Message.unpack_reply(self, header, payload)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/protocol/base.py", line 98, in unpack_reply
    payload, expected_segments=header[4]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/protocol/base.py", line 216, in unpack_from
    yield ReplySegment.unpack(segment_header, segment_payload)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/protocol/base.py", line 232, in unpack
    tuple(Part.unpack_from(payload, expected_parts=header[2]))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/protocol/base.py", line 307, in unpack_from
    part_header[2], part_payload
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhdb/protocol/parts.py", line 111, in unpack_data
    raise Exception("Unknown option type %s" % typ)
Exception: Unknown option type 30

Please fix this.

**Comment by jarus** [comment] 2015-02-20 20:21
Hi,

thank you for the issue. The problem is already fixed in master by pull request #3. To get the fixed version just install pyhdb from the git repo.
We will release sone a version which includes the fix on PyPi.

Best regards,
Christoph

**Comment by dpdornseifer** [comment] 2015-04-24 00:02
Hi have you already pushed the fixed release onto PyPi?

2015-04-23T16:55:43.60-0700 [App/0]      OUT Unknown option type 30
2015-04-23T16:55:43.60-0700 [App/0]      OUT <type 'exceptions.Exception'>
2015-04-23T16:55:43.60-0700 [App/0]      OUT ('Unknown option type 30',)

Best regard,
David

**Comment by bsrdjan** [comment] 2015-04-27 12:03
not yet, will be done. Please clone the repository from GitHub for now.

**Comment by dpdornseifer** [comment] 2015-04-28 18:52
working in a Cloud Foundry environment where all the dependencies are managed via pip, at least in the standard python buildpacks :( - otherwise it's necessary to customize the buildpack and add a install routine to the compile script

**Comment by bsrdjan** [comment] 2015-04-29 07:18
Understood. Could please use from pypitest for the time being ?
```pip install -i https://testpypi.python.org/pypi pyhdb```
Will be released on pypi soon and until then leave the ticket open.

**Comment by dpdornseifer** [comment] 2015-04-29 18:08
great, thx

**Comment by bsrdjan** [comment] 2015-05-21 13:18
released on pypi, closing this one.

**Closed by bsrdjan** 2015-05-21 13:18 UTC
