### ISSUE TITLE
Large SQL statements cannot be executed

### ISSUE THREAD

**Issue by LSriragavan** [SAP/PyHDB#113] opened 2018-11-14 09:17 UTC
The connection class cannot execute SQL statements which are very long (together with data).

I was getting the following error due to this:

```
pyhdb.exceptions.DatabaseError: error while parsing protocol: invalid communication buffer structure
```

The SQL length is 146742.

Is there a way I can increase the buffer size, etc to execute this? I noticed the DEFAULT_CONNECTION_OPTIONS is being used during the connection creation, but not sure whether this can be used. If so, please advice.

**Comment by peterandluc** [comment] 2018-11-29 01:39
What about use fetchall()? Since I can query 2 millions data

**Comment by timmue** [comment] 2018-12-03 14:09
For me the problem is not querying a lot of data, but having an sql command which is very long. Therefore the command itself is not getting executed at all.

**Comment by rybafish** [comment] 2019-12-01 18:44
This error related to the SQL string size and not the result set size.

We had the same problem which was possible to overcome by overriding the MAX_MESSAGE_SIZE value **before** opening the connection:

```
            pyhdb.protocol.constants.MAX_MESSAGE_SIZE = 2**19
            pyhdb.protocol.constants.MAX_SEGMENT_SIZE = pyhdb.protocol.constants.MAX_MESSAGE_SIZE - 32
            
            connection = pyhdb.connect(...)
```

The default value is  2**17, which is about 130KB.

**Comment by bsrdjan** [comment] 2021-05-04 17:44
Closing due to the sunset of the project. Please check active maintained alternative: https://pypi.org/project/hdbcli/

**Closed by bsrdjan** 2021-05-04 17:44 UTC
